name: Re-train Model with MLflow + Docker

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: telco-env
        environment-file: MLProject/conda.yaml
        create-args: >-
          python=3.12

    - name: Run MLflow Project
      shell: micromamba-shell {0}
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Upload MLflow Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/mlruns

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image via MLflow
      run: |
        cd MLProject
        mlflow models build-docker -m ./mlruns/0/*/artifacts/model -n telco-churn-model

    - name: Push Docker Image
      run: |
        docker tag telco-churn-model ${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-model:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/telco-churn-model:latest
