name: Re-train Model with MLflow

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: telco-env
        create-args: >-
          python=3.10
          pip
          pandas
          scikit-learn
          pip:
            mlflow

    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run .
